from enum import Enum


class ExecutionAction(str, Enum):

    PUSH_ROOT = "PUSH_ROOT"

    POP_NODE = "POP_NODE"

    ADD_TO_RESULT = "ADD_TO_RESULT"

    PUSH_LEFT = "PUSH_LEFT"

    PUSH_RIGHT = "PUSH_RIGHT"

    WHILE_CHECK = "WHILE_CHECK"

    RIGHT_CONDITION_CHECK = "RIGHT_CONDITION_CHECK"

    LEFT_CONDITION_CHECK = "LEFT_CONDITION_CHECK"

    WHILE_CHECK_FAILED = "WHILE_CHECK_FAILED"

    SET_CURRENT = "SET_CURRENT"

    MOVE_LEFT = "MOVE_LEFT"

    MOVE_RIGHT = "MOVE_RIGHT"

    PUSH_TO_STACK = "PUSH_TO_STACK"

    INNER_WHILE_CHECK = "INNER_WHILE_CHECK"

    INNER_WHILE_FAILED = "INNER_WHILE_FAILED"